export const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/fEe5fe82qHzjO4yej0o79etqsWV.jpg",
      genre_ids: [16, 35, 28, 10751, 80],
      id: 629542,
      original_language: "en",
      original_title: "The Bad Guys",
      overview:
        "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
      popularity: 2878.099,
      poster_path: "/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
      release_date: "2022-03-17",
      title: "The Bad Guys",
      video: false,
      vote_average: 7.8,
      vote_count: 422,
    },
    {
      adult: false,
      backdrop_path: "/a9zFUuxzChmAlIybVge9IZt1hH0.jpg",
      genre_ids: [35],
      id: 578908,
      original_language: "en",
      original_title: "Bad Trip",
      overview:
        "Two pals embark on a road trip full of funny pranks that pull real people into mayhem.",
      popularity: 68.936,
      poster_path: "/A1Gy5HX3DKGaNW1Ay30NTIVJqJ6.jpg",
      release_date: "2020-09-26",
      title: "Bad Trip",
      video: false,
      vote_average: 6.1,
      vote_count: 366,
    },
    {
      adult: false,
      backdrop_path: "/3N316jUSdhvPyYTW29G4v9ebbcS.jpg",
      genre_ids: [53, 28, 80],
      id: 38700,
      original_language: "en",
      original_title: "Bad Boys for Life",
      overview:
        "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
      popularity: 79.752,
      poster_path: "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
      release_date: "2020-01-15",
      title: "Bad Boys for Life",
      video: false,
      vote_average: 7.2,
      vote_count: 7004,
    },
    {
      adult: false,
      backdrop_path: "/wOLTJxfv98miIQcn0oNXq9fIgXM.jpg",
      genre_ids: [28, 35, 80, 53],
      id: 9737,
      original_language: "en",
      original_title: "Bad Boys",
      overview:
        "Marcus Burnett is a hen-pecked family man. Mike Lowry is a foot-loose and fancy free ladies' man. Both are Miami policemen, and both have 72 hours to reclaim a consignment of drugs stolen from under their station's nose. To complicate matters, in order to get the assistance of the sole witness to a murder, they have to pretend to be each other.",
      popularity: 35.895,
      poster_path: "/x1ygBecKHfXX4M2kRhmFKWfWbJc.jpg",
      release_date: "1995-04-07",
      title: "Bad Boys",
      video: false,
      vote_average: 6.8,
      vote_count: 5169,
    },
    {
      adult: false,
      backdrop_path: "/ttiKTvoeDvl5flghO5s4AV3lLAe.jpg",
      genre_ids: [53, 10770],
      id: 375846,
      original_language: "en",
      original_title: "Bad Sister",
      overview:
        "As a top student at St. Adeline's Catholic Boarding School, Zoe senses that something is not quite right about the school's new nun-- a sense proven to be true when it is revealed the \"good' nun is an imposter with a fatal attraction to Zoe's brother.",
      popularity: 32.175,
      poster_path: "/jKrIlgfJPIWNeowaOZPBZuOPmq0.jpg",
      release_date: "2016-01-03",
      title: "Bad Sister",
      video: false,
      vote_average: 6.8,
      vote_count: 183,
    },
    {
      adult: false,
      backdrop_path: "/gxSVZCUlDd8upT1G2wdrUdz2hxG.jpg",
      genre_ids: [12, 28, 35, 53, 80],
      id: 8961,
      original_language: "en",
      original_title: "Bad Boys II",
      overview:
        "Out-of-control, trash-talking buddy cops Marcus Burnett and Mike Lowrey of the Miami Narcotics Task Force reunite, and bullets fly, cars crash and laughs explode as they pursue a whacked-out drug lord from the streets of Miami to the barrios of Cuba. But the real fireworks result when Marcus discovers that playboy Mike is secretly romancing Marcus’ sexy sister.",
      popularity: 43.712,
      poster_path: "/yCvB5fG5aEPqa1St7ihY6KEAsHD.jpg",
      release_date: "2003-07-18",
      title: "Bad Boys II",
      video: false,
      vote_average: 6.6,
      vote_count: 4444,
    },
    {
      adult: false,
      backdrop_path: "/8YrOggakLM3E6BQ4M61yf2Vn2zi.jpg",
      genre_ids: [35],
      id: 52449,
      original_language: "en",
      original_title: "Bad Teacher",
      overview:
        "A lazy, incompetent middle school teacher who hates her job and her students is forced to return to her job to make enough money for a boob job after her rich fiancé dumps her.",
      popularity: 22.602,
      poster_path: "/zpIY4qUSX91J9XpPgr0hFrk1eKr.jpg",
      release_date: "2011-05-16",
      title: "Bad Teacher",
      video: false,
      vote_average: 5.6,
      vote_count: 4040,
    },
    {
      adult: false,
      backdrop_path: "/pY1t81Lo2ctRX0hGxPvwuFb7RF6.jpg",
      genre_ids: [35],
      id: 208134,
      original_language: "en",
      original_title: "Jackass Presents: Bad Grandpa",
      overview:
        "86-year-old Irving Zisman is on a journey across America with the most unlikely companion: his 8 year-old grandson, Billy.",
      popularity: 34.362,
      poster_path: "/dDSMzBEaM0LYSy9Muo0zsCo77Vh.jpg",
      release_date: "2013-10-22",
      title: "Jackass Presents: Bad Grandpa",
      video: false,
      vote_average: 6.1,
      vote_count: 1314,
    },
    {
      adult: false,
      backdrop_path: "/7lcwCb9DqQxffR5xdJZPOsxkxPL.jpg",
      genre_ids: [35],
      id: 376659,
      original_language: "en",
      original_title: "Bad Moms",
      overview:
        "When three overworked and under-appreciated moms are pushed beyond their limits, they ditch their conventional responsibilities for a jolt of long overdue freedom, fun, and comedic self-indulgence.",
      popularity: 17.893,
      poster_path: "/9PaIkUnfOcU1wi5cFbamnmAkjEs.jpg",
      release_date: "2016-07-28",
      title: "Bad Moms",
      video: false,
      vote_average: 6.5,
      vote_count: 3612,
    },
    {
      adult: false,
      backdrop_path: "/xk7gyLrU2t7CRS1sFGR69QTzA9y.jpg",
      genre_ids: [35, 27],
      id: 172828,
      original_language: "en",
      original_title: "Bad Milo!",
      overview:
        "A horror comedy centered on a guy who learns that his unusual stomach problems are being caused by a demon living in his intestines.",
      popularity: 11.27,
      poster_path: "/1dmHunFILNXKzjOkl1A7IIsTI58.jpg",
      release_date: "2013-08-28",
      title: "Bad Milo!",
      video: false,
      vote_average: 5.7,
      vote_count: 194,
    },
    {
      adult: false,
      backdrop_path: "/nwfpBjtMNFwrGjW2o9HBhMEYCpM.jpg",
      genre_ids: [878, 28, 16],
      id: 366924,
      original_language: "en",
      original_title: "Batman: Bad Blood",
      overview:
        "Bruce Wayne is missing. Alfred covers for him while Nightwing and Robin patrol Gotham City in his stead and a new player, Batwoman, investigates Batman's disappearance.",
      popularity: 21.912,
      poster_path: "/1UmPJWfaivtNjsScJqcsbsQRGNY.jpg",
      release_date: "2016-08-04",
      title: "Batman: Bad Blood",
      video: false,
      vote_average: 7.2,
      vote_count: 588,
    },
    {
      adult: false,
      backdrop_path: "/7bhewNqPoDMneXO4z67vK7LekDB.jpg",
      genre_ids: [18, 28, 80],
      id: 256731,
      original_language: "en",
      original_title: "Bad Country",
      overview:
        "When Baton Rouge police detective Bud Carter busts contract killer Jesse Weiland, he convinces Jesse to become an informant and rat out the South's most powerful crime ring.",
      popularity: 15.915,
      poster_path: "/557r9wTsHdf0ae3MJYihepIZWs3.jpg",
      release_date: "2014-09-26",
      title: "Bad Country",
      video: false,
      vote_average: 5.6,
      vote_count: 143,
    },
    {
      adult: false,
      backdrop_path: "/gBLd5TF8QkAaMGzsMWMRt88S1Dz.jpg",
      genre_ids: [18, 80],
      id: 11699,
      original_language: "en",
      original_title: "Bad Lieutenant: Port of Call - New Orleans",
      overview:
        "Terrence McDonagh is a New Orleans Police sergeant, who recieves a medal and a promotion to lieutenant for heroism during Hurricane Katrina. Due to his heroic act, McDonagh injures his back and becomes addicted to prescription pain medication. He then finds himself involved with a drug dealer who is suspected of murdering a family of African immigrants.",
      popularity: 49.265,
      poster_path: "/zRULXsd0rb1lVfnSyQkYPi2nLcB.jpg",
      release_date: "2009-05-21",
      title: "Bad Lieutenant: Port of Call - New Orleans",
      video: false,
      vote_average: 6.1,
      vote_count: 866,
    },
    {
      adult: false,
      backdrop_path: "/hFtgAVESS9EiIlvCmNCVs31SEYK.jpg",
      genre_ids: [53, 80, 27],
      id: 467632,
      original_language: "en",
      original_title: "Bad Samaritan",
      overview:
        "A thief makes a disturbing discovery in the house where he breaks in. Later, when he returns to the same house with his partner in crime, things are no longer how he expected.",
      popularity: 14.006,
      poster_path: "/fOG5Cj9URclWa0zyESPBuRCvAFh.jpg",
      release_date: "2018-04-19",
      title: "Bad Samaritan",
      video: false,
      vote_average: 6.7,
      vote_count: 530,
    },
    {
      adult: false,
      backdrop_path: "/8UOJBcEHZgOK8BeyEfKnp5Vs0Dy.jpg",
      genre_ids: [18, 35, 80],
      id: 10147,
      original_language: "en",
      original_title: "Bad Santa",
      overview:
        "A miserable conman and his partner pose as Santa and his Little Helper to rob department stores on Christmas Eve. But they run into problems when the conman befriends a troubled kid.",
      popularity: 13.391,
      poster_path: "/dt30keB9txHjYXuMzrqv6uJ499B.jpg",
      release_date: "2003-11-26",
      title: "Bad Santa",
      video: false,
      vote_average: 6.5,
      vote_count: 1703,
    },
    {
      adult: false,
      backdrop_path: "/aQ06MnEDLh9X3ZOtY21UD2XB197.jpg",
      genre_ids: [18, 27, 878],
      id: 316154,
      original_language: "en",
      original_title: "The Bad Batch",
      overview:
        "In a desert wasteland in Texas, a muscled cannibal breaks one important rule: don’t play with your food.",
      popularity: 17.696,
      poster_path: "/7o14VaMphEIzPwzeW6FP3A6zb4W.jpg",
      release_date: "2017-06-23",
      title: "The Bad Batch",
      video: false,
      vote_average: 5.3,
      vote_count: 864,
    },
    {
      adult: false,
      backdrop_path: "/9oLrsekWm3sfEGw5HOav6roW1h7.jpg",
      genre_ids: [28, 12, 35, 53],
      id: 3132,
      original_language: "en",
      original_title: "Bad Company",
      overview:
        "When a Harvard-educated CIA agent is killed during an operation, the secret agency recruits his twin brother.",
      popularity: 9.842,
      poster_path: "/umu141mcfIEhRLgyQp7TWlGJFW.jpg",
      release_date: "2002-06-07",
      title: "Bad Company",
      video: false,
      vote_average: 5.4,
      vote_count: 592,
    },
    {
      adult: false,
      backdrop_path: "/duo6SF2GpG9bz3ymoyInyRl5CLO.jpg",
      genre_ids: [18, 53, 10770],
      id: 969584,
      original_language: "en",
      original_title: "Bad Influence",
      overview:
        "A single mom is overjoyed when her daughter finally makes friends at her new high school. Soon, however, it becomes clear that this group of students follows their own moral code that’s strange, self-centered, and possibly dangerous.",
      popularity: 14.463,
      poster_path: null,
      release_date: "2022-05-20",
      title: "Bad Influence",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/yIpaahwOBk4uVUBNcHkoZdcXPCK.jpg",
      genre_ids: [80, 18, 53],
      id: 13633,
      original_language: "en",
      original_title: "Bad Boys",
      overview:
        "Mick O'Brien is a young Chicago street thug torn between a life of petty crime and the love of his girlfriend. But when the heist of a local drug dealer goes tragically wrong Mick is sentenced to a brutal juvenile prison where violence is a rite of passage and respect is measured in vengeance.",
      popularity: 11.859,
      poster_path: "/5nHZ3wflOifKJMUcTCw0isKhmCv.jpg",
      release_date: "1983-03-25",
      title: "Bad Boys",
      video: false,
      vote_average: 7.1,
      vote_count: 196,
    },
    {
      adult: false,
      backdrop_path: "/lliLm5qfg8lbTCMHSuZ2Dup5HCM.jpg",
      genre_ids: [10749, 37],
      id: 11853,
      original_language: "en",
      original_title: "Bad Girls",
      overview:
        "Four former harlots try to leave the wild west (Colorado, to be exact) and head north to make a better life for themselves. Unfortunately someone from Cody's past won't let it happen that easily.",
      popularity: 12.175,
      poster_path: "/cXY79luLXt2dzUP2Tx601zpZFzK.jpg",
      release_date: "1994-04-22",
      title: "Bad Girls",
      video: false,
      vote_average: 5.4,
      vote_count: 175,
    },
  ],
  total_pages: 97,
  total_results: 1928,
};

export const genres = {
  genres: [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 14, name: "Fantasy" },
    { id: 36, name: "History" },
    { id: 27, name: "Horror" },
    { id: 10402, name: "Music" },
    { id: 9648, name: "Mystery" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Science Fiction" },
    { id: 10770, name: "TV Movie" },
    { id: 53, name: "Thriller" },
    { id: 10752, name: "War" },
    { id: 37, name: "Western" },
  ],
};
